### ISSUE TITLE
Song Titles Won't Refresh

### ISSUE THREAD

**Issue by McDoogle523** [calvinmikael/Radio#2]
When using the app, the currently playing song title will not refresh. The music will continue to play just fine, but in order to see the currently-playing song title I have to close and reopen the app. 

I'm on an iPhone 6 with iOs 10.2.1

**Comment by calvinmikael** [comment]
Could you clarify whether it is the song title on the lock screen or the within the app? The lock screen song title should continue to update even if the app is in the background, however when the app is put in the background it won't update the view which includes the song title unless it has a good reason such as invalid or out of date information. That corrects itself within 10 seconds.

**Comment by calvinmikael** [comment]
Closed until further information is acquired.
